# (C) Copyright IBM 2026.
# (C) Copyright UKRI-STFC (Hartree Centre) 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.


import json
import numpy as np
import pickle as pkl
from adaptaqc.utils.utilityfunctions import qiskit_to_tenpy_mps
from qiskit.qasm3 import loads
from qiskit_aer import AerSimulator
from qiskit_addon_aqc_tensor.simulation import tensornetwork_from_circuit
from tenpy import Array, MPS
from typing import List, Tuple


def string_expectation_values(mps: MPS, s: int, avoid: int = 20) -> Tuple[List]:
    """
    Function to calculate the string expectation values.

    Example with s=0:
        even_values = [
            - <Z_0 Z_1>,
            + <Z_0 Z_1 Z_2 Z_3>,
            - <Z_0 Z_1 Z_2 Z_3 Z_4 Z_5>,
            ...
        ]

        odd_values = [
            - <Z_1 Z_2>,
            + <Z_1 Z_2 Z_3 Z_4>,
            - <Z_1 Z_2 Z_3 Z_4 Z_5 Z_6>,
            ...
        ]

    Args:
        mps (MPS): The matrix product state for which to calculate the expectation values.
        s (int): The starting index for even strings (s+1 for odd strings). Must be even.
        avoid (int): The number of sites closest to the edges to avoid. Must be less than or equal
                    to s.
    Returns:
        even_values (List): Element j corresponds to (-1)^(j+1)*<Z_s...Z_{s+2j+1}).
        odd_values (List): Element j corresponds to (-1)^(j+1)*<Z_{s+1}...Z_{s+2j+2}).
    """

    assert s % 2 == 0
    assert avoid <= s

    # Pauli Z in SpinSite basis convention.
    op = Array.from_ndarray_trivial(
        np.array([[-1, 0], [0, 1]]),
        labels=["p", "p*"],
    )

    even_values = []
    odd_values = []
    for j in range(0, mps.L // 2):
        if s + 2 * j + 1 < mps.L - avoid:
            # Even string order (starts on an even qubit, ends on an odd one).
            # (-1)*<Z_s(iZ_{s+1})...(iZ_{s+2j}Z_{s+2j+1}) = (-1)^(j+1)*<Z_s...Z_{s+2j+1})
            # Starts at s (even), 2(j+1) total terms, j=0,1,2,...
            # If s=0, -Z0Z1, +Z0Z1Z2Z3, -Z0Z1Z2Z3Z4Z5, ...
            # NOTE: we avoid any sites within `start_index` of the ends of the chain.
            even_values.append(
                mps.expectation_value_multi_sites(operators=[op] * 2 * (j + 1), i0=s)
                * (-1) ** (j + 1)
            )

        if s + 2 * j + 2 < mps.L - avoid:
            # Odd string-order (starts on an odd qubit, ends on an even one).
            # (-1)*<Z_{s+1}(iZ_{s+2})...(iZ_{s+2j+1}Z_{s+2j+2}) = (-1)^(j+1)*<Z_{s+1}...Z_{s+2j+2})
            # Starts at s+1 (odd), 2(j+1) total terms, j=0,1,2,...
            # If s=0, -Z1Z2, +Z1Z2Z3Z4, -Z1Z2Z3Z4Z5Z6, ...
            odd_values.append(
                mps.expectation_value_multi_sites(
                    operators=[op] * 2 * (j + 1), i0=s + 1
                )
                * (-1) ** (j + 1)
            )

    return even_values, odd_values


def load_mps_from_file(fn: str, ran_layers: int = 1) -> MPS:
    """
    Function to extract a TeNPy MPS from one of three classes of saved files:
    1. '.pkl' - assumed to be a saved Qiskit MPS.
    2. '.txt' - assumed to be a Qiskit qasm file.
    3. '.json' - assumed to be a Ran method metrics file, generated by
                `legs/comparison_to_other_techniques/schon_and_ran_method.py`.

    Args:
        fn (str): relative file path of the file.
        ran_layers (int): the number of Ran layers to use (only relevant for .json files).
    Returns:

    """
    if fn.endswith(".pkl"):
        with open(fn, "rb") as file:
            qiskit_mps = pkl.load(file)

        tenpy_mps = qiskit_to_tenpy_mps(qiskit_mps)

        return tenpy_mps

    elif fn.endswith(".txt"):
        # QASM file
        with open(fn, "r") as file:
            qasm_string = file.read()

        qc = loads(qasm_string)

    elif fn.endswith(".json"):
        # Ran metrics JSON
        with open(fn, mode="r") as file:
            metrics = json.load(file)

        qasm_string = metrics[str(ran_layers)]["circuit"]
        qc = loads(qasm_string)

    else:
        raise ValueError("Unknown file format.")

    qiskit_mps = tensornetwork_from_circuit(
        qc,
        AerSimulator(
            method="matrix_product_state",
            matrix_product_state_truncation_threshold=1e-16,
            matrix_product_state_max_bond_dimension=50,
        ),
    )
    tenpy_mps = qiskit_to_tenpy_mps(qiskit_mps._as_tuple())

    return tenpy_mps
